export const countryData = [
    { code: "+93", isoCode: "AF", name: "Afghanistan", maxLength: 9 },
    { code: "+1-268", isoCode: "AG", name: "Antigua and Barbuda", maxLength: 7 },
    { code: "+54", isoCode: "AR", name: "Argentina", maxLength: 10 },
    { code: "+61", isoCode: "AU", name: "Australia", maxLength: 9 },
    { code: "+43", isoCode: "AT", name: "Austria", maxLength: 10 },
    { code: "+994", isoCode: "AZ", name: "Azerbaijan", maxLength: 9 },
    { code: "+880", isoCode: "BD", name: "Bangladesh", maxLength: 10 },
    { code: "+32", isoCode: "BE", name: "Belgium", maxLength: 9 },
    { code: "+975", isoCode: "BT", name: "Bhutan", maxLength: 8 },
    { code: "+55", isoCode: "BR", name: "Brazil", maxLength: 11 },
    { code: "+359", isoCode: "BG", name: "Bulgaria", maxLength: 9 },
    { code: "+1-345", isoCode: "KY", name: "Cayman Islands", maxLength: 10 },
    { code: "+86", isoCode: "CN", name: "China", maxLength: 11 },
    { code: "+57", isoCode: "CO", name: "Colombia", maxLength: 10 },
    { code: "+506", isoCode: "CR", name: "Costa Rica", maxLength: 8 },
    { code: "+385", isoCode: "HR", name: "Croatia", maxLength: 9 },
    { code: "+20", isoCode: "EG", name: "Egypt", maxLength: 10 },
    { code: "+33", isoCode: "FR", name: "France", maxLength: 9 },
    { code: "+49", isoCode: "DE", name: "Germany", maxLength: 11 },
    { code: "+91", isoCode: "IN", name: "India", maxLength: 10 },
    { code: "+62", isoCode: "ID", name: "Indonesia", maxLength: 10 },
    { code: "+39", isoCode: "IT", name: "Italy", maxLength: 10 },
    { code: "+81", isoCode: "JP", name: "Japan", maxLength: 10 },
    { code: "+234", isoCode: "NG", name: "Nigeria", maxLength: 11 },
    { code: "+63", isoCode: "PH", name: "Philippines", maxLength: 10 },
    { code: "+351", isoCode: "PT", name: "Portugal", maxLength: 9 },
    { code: "+7", isoCode: "RU", name: "Russia", maxLength: 10 },
    { code: "+27", isoCode: "ZA", name: "South Africa", maxLength: 9 },
    { code: "+82", isoCode: "KR", name: "South Korea", maxLength: 11 },
    { code: "+34", isoCode: "ES", name: "Spain", maxLength: 9 },
    { code: "+90", isoCode: "TR", name: "Turkey", maxLength: 10 },
    { code: "+971", isoCode: "AE", name: "United Arab Emirates", maxLength: 9 },
    { code: "+44", isoCode: "GB", name: "United Kingdom", maxLength: 10 },
    { code: "+1", isoCode: "US", name: "United States", maxLength: 10 },
  ];
  